### PR TITLE
added a new quote on courage (by rocky).

### PR DESCRIPTION
**Pull request by Lon3r-101**
Added source and tags too.(line 3509)

### CODE REVIEW

**Comment by anii-py** [comment]
why?

**Comment by nelsonic** [comment]
@anii-py the continuous integration build fails because there's a JSON parsing error: 
https://travis-ci.com/github/dwyl/quotes/builds/184545544#L217
image

**Comment by pscheid92** [comment]
I see no action on this pull request for several months, so what should we do about it?

The error is due to missing commas at the end of lines.\
I could fix them, if that is ok with you @nelsonic.

**Comment by Lon3r-101** [comment]
case closed.

**Pull request closed without merging**
