### PR TITLE
add some quotes to the json file

### PR DESCRIPTION
**Pull request by shaund16**

### CODE REVIEW

**Review by nelsonic — APPROVED** [review]
Thanks @shaund16. 👍🏻
would be good to have source and tags for these. 💭

**Comment by shaund16** [comment]
Fixed!

**Comment by nelsonic** [comment]
I've attempted to fix the **`merge-conflicts`** in the `quotes.json` file.
But as noted in https://github.com/dwyl/learn-travis/issues/67 Travis Builds aren't working.  
I've done a _manual_ check and the file appears to pass https://jsonlint.com/ as **Valid JSON**:

image

Happy to merge. 👍

**Review by nelsonic — APPROVED** [review]
@shaund16 thanks for adding these quotes. 👍 
They don't _strictly_ inspire action. 💭 
But happy to merge them as you've made the effort to add them and they don't _detract_ from the action-inspiring quotes. 
Thanks again. ☀️

**Pull request merged**
