### PR TITLE
Add new lib functions

### PR DESCRIPTION
**Pull request by growthbeing**
### New quotes library functions for Javascript
- [x] Added quotes.random_by_author
- [x] Added quotes.random_by_source
- [x] Added tests for the quotes.random_by_author & quotes.random_by_source

### CODE REVIEW

**Comment by nelsonic** [comment]
@growthbeing we knew you would find us _eventually_! ❤️ 
First PR! We are honoured. Very much welcome! 🎉 
Write access granted: https://github.com/dwyl/quotes/invitations 📝 
Visit https://github.com/dwyl to accept org invitation. 📥 
Welcome to the community! 🙌

**Review by nelsonic — APPROVED** [review]
@growthbeing thank you for extending the JS functions with tests. 🎉

**Comment by growthbeing** [comment]
> @growthbeing thank you for extending the JS functions with tests. tada

@nelsonic You're welcome. :+1:

**Comment by nelsonic** [comment]
@growthbeing `quotesy@1.0.8` published to NPM contains these functions. Thanks again. 🚀

**Pull request merged**
